apiVersion: apps/v1 # This says we are creating a Deployment using Kubernetes API version "apps/v1"
kind: Deployment # The type of object we want to create is a Deployment
metadata:
  name: comments-depl # The name of this Deployment will be "posts-depl"

spec:
  replicas: 1 # Run 1 copy (pod) of this application
  selector:
    matchLabels:
      app: comments # This Deployment will look for pods with the label "app: posts"

  template: # Define how the pods should look
    metadata:
      labels:
        app: comments # Every pod created will have the label "app: posts"

    spec:
      containers: # List of containers inside each pod
        - name: comments # Name of the container is "posts"
          image: vikash199/comments # Use the container image "vikash/posts:0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001
