apiVersion: apps/v1 # This says we are creating a Deployment using Kubernetes API version "apps/v1"
kind: Deployment # The type of object we want to create is a Deployment
metadata:
  name: event-bus-depl # The name of this Deployment will be "posts-depl"

spec:
  replicas: 1 # Run 1 copy (pod) of this application
  selector:
    matchLabels:
      app: event-bus # This Deployment will look for pods with the label "app: posts"

  template: # Define how the pods should look
    metadata:
      labels:
        app: event-bus # Every pod created will have the label "app: posts"

    spec:
      containers: # List of containers inside each pod
        - name: event-bus # Name of the container is "posts"
          image: vikash199/event-bus # Use the container image "vikash/posts:0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005
