apiVersion: apps/v1 # This says we are creating a Deployment using Kubernetes API version "apps/v1"
kind: Deployment # The type of object we want to create is a Deployment
metadata:
  name: moderation-depl # The name of this Deployment will be "posts-depl"

spec:
  replicas: 1 # Run 1 copy (pod) of this application
  selector:
    matchLabels:
      app: moderation # This Deployment will look for pods with the label "app: posts"

  template: # Define how the pods should look
    metadata:
      labels:
        app: moderation # Every pod created will have the label "app: posts"

    spec:
      containers: # List of containers inside each pod
        - name: moderation # Name of the container is "posts"
          image: vikash199/moderation # Use the container image "vikash/posts:0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003
