apiVersion: v1
kind: Service
metadata:
  name: posts-sev
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #node port
      targetPort: 4000 #traffic comes on this port
